import { FlowNode } from "../../types";

export const emailTriggerNodes: FlowNode[] = [
  {
    node_id: "EMAIL_TRIGGER",
    icon: "/icons/mail.svg",
    name: "Email Trigger",
    description: "Trigger a flow when an email is received at a unique address",
    type: "trigger",
    provider: "GOALMATIC",
    category: "MESSAGING",
    props: [
      {
        name: "Unique Email Address",
        key: "unique_email",
        type: "email_display",
        required: false,
        disabled: true,
        copyable: true,
        description: "Auto-generated unique email address for this trigger",
        placeholder: "Generating...",
        cloneable: false,
        auto_generate: true,
        generate_on: "node_create",
      },
      {
        name: "Allowed Senders",
        key: "allowed_senders",
        type: "textarea",
        required: false,
        description:
          "Comma-separated list of email addresses that can trigger this flow (leave empty to allow all)",
        placeholder: "user@example.com, admin@company.com",
        cloneable: true,
      },
      {
        name: "Blocked Senders",
        key: "blocked_senders",
        type: "textarea",
        required: false,
        description:
          "Comma-separated list of email addresses that should be blocked from triggering this flow",
        placeholder: "spam@example.com, blocked@domain.com",
        cloneable: true,
      },
      {
        name: "Subject Must Contain",
        key: "subject_contains",
        type: "text",
        required: false,
        description:
          "Comma-separated keywords - email subject must contain at least one of these",
        placeholder: "urgent, important, order",
        cloneable: true,
      },
      {
        name: "Subject Must Not Contain",
        key: "subject_excludes",
        type: "text",
        required: false,
        description:
          "Comma-separated keywords - emails with these in subject will be ignored",
        placeholder: "spam, advertisement, unsubscribe",
        cloneable: true,
      },
      {
        name: "Max Triggers Per Hour",
        key: "max_triggers_per_hour",
        type: "number",
        required: false,
        description:
          "Maximum number of times this trigger can fire per hour (1-1000)",
        placeholder: "60",
        min: 1,
        max: 1000,
        value: 60,
        cloneable: true,
      },
      {
        name: "Max Triggers Per Day",
        key: "max_triggers_per_day",
        type: "number",
        required: false,
        description:
          "Maximum number of times this trigger can fire per day (1-5000)",
        placeholder: "500",
        min: 1,
        max: 5000,
        value: 500,
        cloneable: true,
      },
      {
        name: "Include Attachments",
        key: "include_attachments",
        type: "checkbox",
        required: false,
        description: "Whether to include email attachments in the flow data",
        value: false,
        cloneable: true,
      },
      {
        name: "Max Attachment Size (MB)",
        key: "max_attachment_size_mb",
        type: "number",
        required: false,
        description: "Maximum size of attachments to process (1-50 MB)",
        placeholder: "10",
        min: 1,
        max: 50,
        value: 10,
        cloneable: true,
        showIf: "include_attachments",
      },
      {
        name: "Allowed File Types",
        key: "allowed_file_types",
        type: "text",
        required: false,
        description: "Comma-separated list of allowed file extensions",
        placeholder: "pdf, doc, docx, txt, jpg, png",
        value: "pdf, doc, docx, txt, jpg, png, gif",
        cloneable: true,
        showIf: "include_attachments",
      },
      {
        name: "Send Auto-Reply",
        key: "send_auto_reply",
        type: "checkbox",
        required: false,
        description: "Send an automatic reply when emails are processed",
        value: false,
        cloneable: true,
      },
      {
        name: "Auto-Reply Message",
        key: "auto_reply_message",
        type: "textarea",
        required: false,
        description: "Message to send as auto-reply",
        placeholder:
          "Thank you for your email. We have received it and will process it shortly.",
        cloneable: true,
        showIf: "send_auto_reply",
      },
    ],
  },
];
